# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_id_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
