# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171023_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.CharField(default='trump.jpg', max_length=50),
        ),
    ]
